FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

# Di default, avviamo il client MNIST
CMD ["python", "examples/mnist/Client.py"]
