apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-client-svc
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-client
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-client-stateful
spec:
  serviceName: {{ .Chart.Name }}-client-svc
  replicas: {{ .Values.replicas.client }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-client
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-client
    spec:
      containers:
      - name: fed-client
        image: {{ .Values.client.image }}
        imagePullPolicy: IfNotPresent
        env:
          # Salviamo il nome del pod in una variabile d'ambiente
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Esempio: se HOSTNAME = "federated-learning-client-stateful-0"
            # estraiamo l'indice numerico dopo l'ultimo trattino:
            ID_SUFFIX=$(echo $HOSTNAME | sed 's/.*-//')

            # Avvia il client con quell'indice come "id"
            python examples/mnist/Client.py \
              $ID_SUFFIX \
              --host {{ .Values.client.serverHost }} \
              --port {{ .Values.client.port }}
