apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.evaluations.name }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.volumes.evaluations.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.volumes.evaluations.storageClass }}
  hostPath:
    path: {{ .Values.volumes.evaluations.hostPath }}
