apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.logs.name }}-pvc
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "Missing logs volume size" .Values.volumes.logs.size }}
  storageClassName: {{ .Values.volumes.logs.storageClass | default "manual" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.evaluations.name }}-pvc
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "Missing evaluations volume size" .Values.volumes.evaluations.size }}
  storageClassName: {{ .Values.volumes.evaluations.storageClass | default "manual" }}
