apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-server-svc
spec:
  selector:
    app: {{ .Chart.Name }}-server
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-server-deployment
spec:
  replicas: {{ .Values.replicas.server }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-server
    spec:
      containers:
      - name: fed-server
        image: {{ .Values.server.image }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.server.port }}
        # Esempio: se il tuo Server.py sta in examples/mnist/Server.py
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Esempio: se HOSTNAME = "federated-learning-client-stateful-0"
            # estraiamo l'indice numerico dopo l'ultimo trattino:
            ID_SUFFIX=$(echo $HOSTNAME | sed 's/.*-//')

            # Avvia il client con quell'indice come "id"
            python src/run_experiment.py \
              --experiment {{ .Values.experiment }} \
              --id -1 \
              --numberOfClients {{ .Values.replicas.client }} \
              --numberOfRounds {{.Values.server.numberOfRounds }} \
              --experiment {{ .Values.experiment }} \
              --model {{ .Values.client.model }} \
              --input_shape {{ .Values.server.input_shape | join "," }} \
              --class_names  "{{ .Values.server.class_names | join "," }}"
        volumeMounts:
          - name: logs-volume
            mountPath: {{ .Values.volumes.logs.mountPath }}
          - name: evaluations-volume
            mountPath: {{ .Values.volumes.evaluations.mountPath }}
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.logs.name }}-pvc
        - name: evaluations-volume
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.evaluations.name }}-pvc