apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-server-svc
spec:
  selector:
    app: {{ .Chart.Name }}-server
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-server-deployment
spec:
  replicas: {{ .Values.replicas.server }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-server
    spec:
      containers:
      - name: fed-server
        image: {{ .Values.server.image }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.server.port }}
        # Esempio: se il tuo Server.py sta in examples/mnist/Server.py
        command: ["python"]
        args: ["examples/mnist/Server.py"]
