replicas:
  server: 1
  client: 8

experiment: "mnist"



server:
  image: "fed-server:latest"
  imagePullPolicy: "Always"
  port: 12345
  numberOfRounds: 6
  input_shape: [28, 28]
  class_names: ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine']
client:
  image: "fed-client:latest"
  imagePullPolicy: "IfNotPresent"
  port: 12345
  serverHost: "federated-learning-server-svc"
  model: "src.models.model1"
  datasetLoader: "src.dataLoaders.mnist.datasetLoader"
  loss: "CategoricalCrossentropy"
  lossParams: "{}"
  metric: "CategoricalAccuracy"
  metricParams: "{}"
  optimizer: "Adam"
  optimizerParams: '{"learning_rate": 0.002}'
  numClasses: 10
  batchSize: 32
  trainEpochs: 40

volumes:
  evaluations:
    name: evaluations-volume
    mountPath: /app/output/
    size: 1Gi
    storageClass: manual
    hostPath: /output/